class AddForeignKeyIndices < ActiveRecord::Migration
  def self.up
    add_index :bids, :contract_id
    add_index :components, :project_id
    add_index :components_tags, :component_id
    add_index :components_tags, :tag_id
    add_index :contract_costs, :contract_id
    add_index :contracts, :component_id
    add_index :contracts, :project_id
    add_index :deadlines, :project_id
    add_index :deadlines, :parent_deadline_id
    add_index :fixed_cost_estimates, :component_id
    add_index :fixed_cost_estimates, :task_id
    add_index :invoice_lines, :invoice_id
    add_index :invoices, :project_id
    add_index :labor_cost_lines, :labor_set_id
    add_index :labor_cost_lines, :project_id
    add_index :labor_costs, :project_id
    add_index :markings, :markupable_id
    add_index :markings, :markupable_type
    add_index :markings, :markup_id
    add_index :material_cost_lines, :material_set_id
    add_index :material_costs, :task_id
    add_index :material_costs, :supplier_id
    add_index :milestones, :task_id
    add_index :milestones, :project_id
    add_index :milestones, :parent_date_id
    add_index :milestones, :parent_date_type
    add_index :payment_lines, :payment_id
    add_index :payment_lines, :cost_id
    add_index :payments, :project_id
    add_index :projects_users, :project_id
    add_index :projects_users, :user_id
    add_index :quantities, :component_id
    add_index :tasks, :contract_id
    add_index :tasks, :deadline_id
    add_index :tasks, :project_id
    add_index :unit_cost_estimates, :component_id
    add_index :unit_cost_estimates, :task_id
  end

  def self.down
    remove_index :bids, :contract_id
    remove_index :components, :project_id
    remove_index :components_tags, :component_id
    remove_index :components_tags, :tag_id
    remove_index :contract_costs, :contract_id
    remove_index :contracts, :component_id
    remove_index :contracts, :project_id
    remove_index :deadlines, :project_id
    remove_index :deadlines, :parent_deadline_id
    remove_index :fixed_cost_estimates, :component_id
    remove_index :fixed_cost_estimates, :task_id
    remove_index :invoice_lines, :invoice_id
    remove_index :invoices, :project_id
    remove_index :labor_cost_lines, :labor_set_id
    remove_index :labor_cost_lines, :project_id
    remove_index :labor_costs, :project_id
    remove_index :markings, :markupable_id
    remove_index :markings, :markupable_type
    remove_index :markings, :markup_id
    remove_index :material_cost_lines, :material_set_id
    remove_index :material_costs, :task_id
    remove_index :material_costs, :supplier_id
    remove_index :milestones, :task_id
    remove_index :milestones, :project_id
    remove_index :milestones, :parent_date_id
    remove_index :milestones, :parent_date_type
    remove_index :payment_lines, :payment_id
    remove_index :payment_lines, :cost_id
    remove_index :payments, :project_id
    remove_index :projects_users, :project_id
    remove_index :projects_users, :user_id
    remove_index :quantities, :component_id
    remove_index :tasks, :contract_id
    remove_index :tasks, :deadline_id
    remove_index :tasks, :project_id
    remove_index :unit_cost_estimates, :component_id
    remove_index :unit_cost_estimates, :task_id
  end
end
